Adding output for idempotency check.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -43,6 +43,13 @@ jobs:
           command: |
             docker-compose exec -T ubuntu16 ansible-playbook --skip-tags no_test --connection=local --inventory 127.0.0.1, /home/circleci/project/ansible-os-ubuntu-16/playbook.yml | tee ./ansible_out.log | grep 'changed=0.*failed=0' 
             export LAST_ERR=$?
+            echo $?
             echo "-----Ansible Log From Idempotentency Check-----"
             cat ansible_out.log 
-            test $LAST_ERR && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
+            if [ $LAST_ERR && -nq 0 ]
+            then 
+              echo 'Idempotence test: fail' && exit 1
+            else
+              echo 'Idempotence test: pass'
+            fi
+
