Adding output for idempotency check.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -41,6 +41,8 @@ jobs:
       - run:
           name: Run playbook.yml again, checking to make sure it's idempotent
           command: |
-            docker-compose exec -T ubuntu16 ansible-playbook --skip-tags no_test --connection=local --inventory 127.0.0.1, /home/circleci/project/ansible-os-ubuntu-16/playbook.yml | tee ./ansible_out.log | grep 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
+            docker-compose exec -T ubuntu16 ansible-playbook --skip-tags no_test --connection=local --inventory 127.0.0.1, /home/circleci/project/ansible-os-ubuntu-16/playbook.yml | tee ./ansible_out.log | grep 'changed=0.*failed=0' 
+            export LAST_ERR=$?
             echo "-----Ansible Log From Idempotentency Check-----"
             cat ansible_out.log 
+            test $LAST_ERR && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
